# Generated by Django 4.0.3 on 2022-03-22 03:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='default@gmail.com', max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to='user_auth_api.useraccount')),
                ('location', models.CharField(blank=True, default='unknown', max_length=100)),
                ('favorite_genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('techno', 'Techno'), ('hiphop', 'Hip-hop'), ('jazz', 'Jazz'), ('rap', 'Rap'), ('country', 'Country'), ('metal', 'Metal'), ('alternative', 'Alternative'), ('indie', 'Indie')], default=list, max_length=1000), size=None)),
                ('image', models.CharField(blank=True, default='https://imgur.com/V4RclNb', max_length=100)),
            ],
        ),
    ]
