# Generated by Django 4.0.3 on 2022-03-21 20:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favorite_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('techno', 'Techno'), ('hiphop', 'Hip-hop'), ('jazz', 'Jazz'), ('rap', 'Rap'), ('country', 'Country'), ('metal', 'Metal'), ('alternative', 'Alternative'), ('indie', 'Indie')], default=list, max_length=1000), size=None),
        ),
    ]
