# Generated by Django 4.0.3 on 2022-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
