# Generated by Django 4.0.3 on 2022-03-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.CharField(blank=True, default='https://i.imgur.com/V4RclNb.png', max_length=100),
        ),
    ]
