# Generated by Django 4.0.3 on 2022-03-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0002_remove_account_user_account_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
