# Generated by Django 4.0.3 on 2022-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0003_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='default@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('M', 'Musician'), ('L', 'Listener')], default='L', max_length=1),
        ),
    ]
