# Generated by Django 4.0.3 on 2022-03-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_api', '0004_user_email_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='default@gmail.com', max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
