# Generated by Django 4.0.3 on 2022-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('techno', 'Techno'), ('hiphop', 'Hip-hop'), ('jazz', 'Jazz'), ('rap', 'Rap'), ('country', 'Country'), ('metal', 'Metal'), ('alternative', 'Alternative'), ('indie', 'Indie')], default='pop', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
