# Generated by Django 4.0.3 on 2022-03-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_alter_song_artist_alter_song_audio_alter_song_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.29', max_digits=6),
        ),
    ]
