# Generated by Django 4.0.3 on 2022-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0005_alter_song_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(default='https://i.imgur.com/D3aOVsJ.png', max_length=100),
        ),
    ]
